import { ApiError } from "@/api/errors/ApiError";
import { errorHandlers } from "@/api/errors/errorMessages"

export function useApiError(){
    const handleError = (error: unknown, fallbackMessage: string = 'OcurriÃ³ un error inesperado.', scope: string = ""): string => {
        if(error instanceof ApiError && scope in errorHandlers){ 
            return errorHandlers[scope](error) || fallbackMessage
        }
        
        return fallbackMessage
    }

    return { handleError }
}